SLICING

1-D ARRAY

In [2]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
print(arr[1:4])

[2 3 4]


In [7]:
print(arr[::2])

[1 3 5]


SLICING IN 2-D ARRAY

In [8]:
array2 = np.array([[10,20,30,40],[50,60,70,80]])
print(array2)

[[10 20 30 40]
 [50 60 70 80]]


In [9]:

print(array2[0,:3])

[10 20 30]


CREATING ARRAYS WITH USER-DEFINED DATATYPES

In [11]:
arr = np.array([1,2,3,4,5], dtype = 'S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


CREATING ARRAY WITH 4 BYTES INT

In [12]:
arr = np.array([1,2,3,4,5] , dtype ='i4')
print(arr.dtype)

int32


SHAPE OF AN ARRAY

In [13]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)


(2, 4)


In [14]:
arr = np.array([[[1,2,3,4],[5,6,7,8]]])
print(arr.shape)

(1, 2, 4)


JOINING ARRAYS

In [18]:
arr = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])

arr = np.concatenate((arr,arr2), axis = 0)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


SPLITTING THE ARRAY

In [31]:
arr = np.array([[1,2,3], [5,6,7]])
newarr = np.array_split(arr,3)
print(newarr)

[array([[1, 2, 3]]), array([[5, 6, 7]]), array([], shape=(0, 3), dtype=int32)]


RAVEL AND FLATTEN : Multi to 1d

In [11]:
arr = np.array([[[[1,2,3], [4,5,6], [5,6,7]]]])
print(arr)
print(arr.ndim)



[[[[1 2 3]
   [4 5 6]
   [5 6 7]]]]
4


In [12]:
#n = arr.ravel()  
n = arr.flatten()
print(n.ndim)


1


# UNIQUE FUNCTIONS

In [22]:
k = np.array([1,2,2,2,3,4,4,4,5,6,6,6,7])
print(k)
l = np.unique(arr)
print(l)


[1 2 2 2 3 4 4 4 5 6 6 6 7]
[1 2 3 4 5 6 7]


In [25]:
x = np.unique(k, return_index =True, return_counts =True)
print(x)

(array([1, 2, 3, 4, 5, 6, 7]), array([ 0,  1,  4,  5,  8,  9, 12], dtype=int64), array([1, 3, 1, 3, 1, 3, 1], dtype=int64))


#DELETE

In [30]:
q = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(q)
arr = np.delete(q, 1, axis=0)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
